### ISSUE TITLE
[ERROR] Not compatible with vicuna v1.3 

### ISSUE THREAD

**Issue by CiaoHe** [UCSD-AI4H/drugchat#9]
I tried to use vicuna-7b-v1.3 (the latest released vicuna version). The training process is OK without any error, but when inference using `demo.sh` I countered the error when call the `LlamaModel` forward() function
```
Traceback (most recent call last):
  File "/home/rentianhe/anaconda3/envs/drugchat/lib/python3.9/site-packages/gradio/routes.py", line 393, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/rentianhe/anaconda3/envs/drugchat/lib/python3.9/site-packages/gradio/blocks.py", line 1108, in process_api
    result = await self.call_function(
  File "/home/rentianhe/anaconda3/envs/drugchat/lib/python3.9/site-packages/gradio/blocks.py", line 915, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/rentianhe/anaconda3/envs/drugchat/lib/python3.9/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/rentianhe/anaconda3/envs/drugchat/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/rentianhe/anaconda3/envs/drugchat/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/rentianhe/anaconda3/envs/drugchat/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/comp_robot/rentianhe/caohe/AIDD/drugchat/demo.py", line 103, in gradio_answer
    llm_message = chat.answer(conv=chat_state,
  File "/comp_robot/rentianhe/caohe/AIDD/drugchat/pipeline/conversation/conversation.py", line 151, in answer
    outputs = self.model.llama_model.generate(
  File "/home/rentianhe/anaconda3/envs/drugchat/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/rentianhe/anaconda3/envs/drugchat/lib/python3.9/site-packages/transformers/generation/utils.py", line 1437, in generate
    return self.greedy_search(
  File "/home/rentianhe/anaconda3/envs/drugchat/lib/python3.9/site-packages/transformers/generation/utils.py", line 2248, in greedy_search
    outputs = self(
  File "/home/rentianhe/anaconda3/envs/drugchat/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/comp_robot/rentianhe/caohe/AIDD/drugchat/pipeline/models/modeling_llama.py", line 676, in forward
    outputs = self.model(
  File "/home/rentianhe/anaconda3/envs/drugchat/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/comp_robot/rentianhe/caohe/AIDD/drugchat/pipeline/models/modeling_llama.py", line 517, in forward
    position_ids = position_ids.view(-1, seq_length).long()
RuntimeError: shape '[-1, 29]' is invalid for input of size 30
```

I think it's related to the version of Vicuna, more detailed, the difference of tokenizer/special_token_map config. But I'm not familiar with the forward logic so it's tough for me to debug.
Have you tried train using vicuna-v1.3, just curious.

**Comment by youweiliang** [comment]
Hi He,
We only tested with vicuna-v0 and didn't try using vicuna-v1.3. The doc of Vicuna ([https://github.com/lm-sys/FastChat/blob/main/docs/vicuna_weights_version.md](https://github.com/lm-sys/FastChat/blob/main/docs/vicuna_weights_version.md)) shows that one of the main differences is the separator (v0 uses `###` while v1.3 uses `</s>`). I think you probably need to change the separators in this repo (e.g., in the prompts and in the decoding of text in the conversation) and maybe also the tokenizer to make it compatible with vicuna v1.3.

**Comment by CiaoHe** [comment]
Cool, I will try to replace it with the corresponding version's content.
Btw, I found that the training process only uses stage2 config for fine-tuning. So we just skip the stage-1 aligning (as said in MiniGPT-4)?

**Comment by youweiliang** [comment]
I think the main difference between stage1 and stage2 of MiniGPT-4 is in the datasets, the training procedure is basically the same (training or finetuning the linear projection layer). In our repo, although we use stage2 config, it basically does the things in stage1 (training the linear projection layer).

**Comment by CiaoHe** [comment]
Yeah, I agree. 

We tried to replicate the experiment on 13B, but the result chat doesn't perform ideally (the corresponding description doesn't match the input SMILES). Plz checks the example, we input the SMILES of Nicotine, but the description is about some kind of Alcohol.
![1791688524314_ pic](https://github.com/UCSD-AI4H/drugchat/assets/39040787/6a54d51f-4f5b-4e3d-ba6e-909292df159f)

Our replication process:

1. Data preparation: 

   1. We use the script provided in `dataset/` to convert json files in `data/` into QA pickle file; then merge the two `chembl_qa` and `pubchem_qa`  dataset into one whole train pickle file `dataset/chembl_pubchem_train.pkl`. We checked the train set size: 130458 QA pairs (matched with paper and config file)

   2. > Some questions:
      >
      > 1. We observed that you've left the chembl_qa_test pairs in `data/ChEMBL_QA_test.json`, it should be used in inference. Any future idea on the metrics for the generation content? 
      > 2. When pulling the repository, the original pickle in "chembl_pyg_abs3.pkl" already exists. It contains only 3386 samples. What is the purpose of this part of the data?

2. Training:

   * We didn't change much in the config file. We use 1 A100(40GB) for training 10 epochs where batch_size = 1. Details shown below:
![4401688447429_ pic](https://github.com/UCSD-AI4H/drugchat/assets/39040787/5424e59a-b87f-4445-be03-9b220293781d)

   * We use vicuna-13B v1.0 as LLM
   * We follow the same inference instruction in README
   * The final loss converged to ~0.351 (after 10 epochs)

# Questions:
1. Are there any problems that need attention in the implementation? What are the omissions in our implementation process?
2. Would you kindly provide your trained ckpt for inference? (same ckpt used in demo figure)

Best,

**Comment by youweiliang** [comment]
Hi He,
Your configuration looks fine, so I am not sure whether there is any problem with your replication process. The current repo of DrugChat is still in its early exploration stage and may not be optimal in terms of performance. We are also exploring other approaches for DrugChat but may not plan to release them in the near future until they become more stable and mature. Sorry for the inconvenience. 

Best,
Youwei

**Comment by hzau96yhz** [comment]
> Yeah, I agree.
> 
> We tried to replicate the experiment on 13B, but the result chat doesn't perform ideally (the corresponding description doesn't match the input SMILES). Plz checks the example, we input the SMILES of Nicotine, but the description is about some kind of Alcohol. ![1791688524314_ pic](https://user-images.githubusercontent.com/39040787/251026553-6a54d51f-4f5b-4e3d-ba6e-909292df159f.jpg)
> 
> Our replication process:
> 
> 1. Data preparation:
>    
>    1. We use the script provided in `dataset/` to convert json files in `data/` into QA pickle file; then merge the two `chembl_qa` and `pubchem_qa`  dataset into one whole train pickle file `dataset/chembl_pubchem_train.pkl`. We checked the train set size: 130458 QA pairs (matched with paper and config file)
>    2. > Some questions:
>       > 
>       > 1. We observed that you've left the chembl_qa_test pairs in `data/ChEMBL_QA_test.json`, it should be used in inference. Any future idea on the metrics for the generation content?
>       > 2. When pulling the repository, the original pickle in "chembl_pyg_abs3.pkl" already exists. It contains only 3386 samples. What is the purpose of this part of the data?
> 2. Training:
>    
>    * We didn't change much in the config file. We use 1 A100(40GB) for training 10 epochs where batch_size = 1. Details shown below:
>      ![4401688447429_ pic](https://user-images.githubusercontent.com/39040787/251028758-5424e59a-b87f-4445-be03-9b220293781d.jpg)
>    * We use vicuna-13B v1.0 as LLM
>    * We follow the same inference instruction in README
>    * The final loss converged to ~0.351 (after 10 epochs)
> 
> # Questions:
> 1. Are there any problems that need attention in the implementation? What are the omissions in our implementation process?
> 2. Would you kindly provide your trained ckpt for inference? (same ckpt used in demo figure)
> 
> Best,

Hi @CiaoHe，Is the front-end interface an extra program you wrote？

**Comment by CiaoHe** [comment]
no. It's contained in the repo.

**Comment by hzau96yhz** [comment]
Thank you for you timely reply！
I have another question, according to the article description, the training process should be fine tuning the weight of the projection layer, so why did the author set up pre-training stage 1(drugchat_stage1_pretrain.yaml) and fine tuning stage 2(drugchat_stage2_finetune.yaml) in the **train_configs**？

There doesn't seem to be any mention of pre-training in the article, and neither does the pre-training dataset. It seems that pre-trained GNN and LLM are directly using other articles. Maybe my understanding of the article is wrong, I hope to get a professional answer.
@CiaoHe @youweiliang

**Comment by youweiliang** [comment]
The existence of the two files you mentioned is for legacy reasons. You can use any of them to train/finetune the projection layer. The only difference is whether you provide a checkpoint path to the config. When you don't provide a checkpoint path, you are in the pre-training stage, and when you provide a checkpoint path, you are in the fine tuning stage. It doesn't matter how these files are named.

In the training process, we train the weight of the projection layer from scratch. There is no checkpoint to use and there is no pretraining dataset.

**Comment by hzau96yhz** [comment]
I understand. Thank you very much for your answer！

**Comment by hzau96yhz** [comment]
@CiaoHe Hello！When replicating the demo, have you ever encountered the problem that after entering the molecular SMILES string, the system keeps loading and the user cannot enter it.
